name: "🐞 SLA Bug Report"
description: "File a bug/issue."
title: "Replace with Your Title"
labels: [bug, sla]
assignees:
  - yalla-coop-sla
  - AbdelhalimOJ
body:
  - type: dropdown
    id: priority
    attributes:
      label: "Please select the priority level:"
      description: >
        • **Priority-1 (Critical – Needs Immediate Attention):** This bug is **urgent** and severely impacts functionality, security, or stability. It may cause crashes, data loss, security breaches, or prevent key workflows from functioning. Immediate action is required.  

        
        • **Priority-2 (High – Fix This Week):** This bug affects a **core feature** or disrupts the user experience. It’s not as urgent as Priority-1 but should be resolved within the week to avoid major issues or client dissatisfaction.  


        • **Priority-3 (Normal – Fix Within the Month):** This is a **moderate-impact bug** that doesn’t block core functionality but still affects a portion of users or a specific workflow. Resolution should happen within the current or next cycle.  


        • **Priority-4 (Low – Cosmetic or Minor):** This is a **low-impact issue**, such as a styling bug, UI alignment problem, or small inconsistency. It does not affect usability and can be handled during routine maintenance.
      options:
        - Priority-1 (Critical – Needs Immediate Attention)
        - Priority-2 (High – Fix This Week)
        - Priority-3 (Normal – Fix Within the Month)
        - Priority-4 (Low – Cosmetic or Minor)
    validations:
      required: true

  - type: dropdown
    id: review
    attributes:
      label: "Would you like to review the fix before it goes live?"
      description: >
        If this bug impacts clients or core workflows, you may want to review the solution before it’s released. Let us know your preference.
      options:
        - Yes, I would like to review the fix before it goes live.
        - No, you can push the fix directly to production without a review from me.
      multiple: false
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Describe the bug and the expected behaviour."
      description: "A clear and concise description of the bug you're experiencing and what you expected to happen."
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Steps To Reproduce"
      description: "Steps to reproduce the behavior."
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
    validations:
      required: false

  - type: textarea
    attributes:
      label: "Screenshots or a link to a Loom Recording"
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.

  - type: dropdown
    id: browsers
    attributes:
      label: "What browsers are you seeing the problem on?"
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Other

  - type: textarea
    attributes:
      label: "Anything else?"
      description: |
        Add any other information you think might be relevant or provide context.
    validations:
      required: false
