name: "💡 SLA Feature Request"
description: "File a request for a new feature or update."
title: "Replace with Your Title"
labels: [enhancement, sla]
assignees:
  - yalla-coop-sla
  - AbdelhalimOJ
body:
  - type: dropdown
    id: priority
    attributes:
      label: "Please select the priority level:"
      description: >
        • **Priority-1 (Critical – Needed Urgently):** This feature is business-critical and needs to be delivered as soon as possible. It may be required to meet a client deadline, fulfill a contractual obligation, or unblock a key process. Delays may directly impact delivery, operations, or commitments you've made to your own stakeholders.


        • **Priority-2 (High – Needed Soon):** Important to your workflow or goals and should be prioritised in the near term. Not immediately urgent, but adds clear value and should be scheduled in the next cycle.


        • **Priority-3 (Normal – Nice to Have):** Useful improvement that makes things smoother or more efficient but isn’t blocking anything. Can be planned into a future update.


        • **Priority-4 (Low – Future Wishlist):** Non-essential idea that’s not time-sensitive. May be exploratory or future-facing. Logged for future planning when capacity allows.
      options:
        - Priority-1 (Critical – Needed Urgently)
        - Priority-2 (High – Needed Soon)
        - Priority-3 (Normal – Nice to Have)
        - Priority-4 (Low – Future Wishlist)
    validations:
      required: true

  - type: dropdown
    id: review
    attributes:
      label: "Would you like to see a demo of this feature before it goes live?"
      description: >
        If this feature affects a client, changes visible functionality, or alters a key workflow, we recommend reviewing it before deployment. Let us know if you'd like a demo or prefer it to go straight to production.
      options:
        - Yes, I would like to review a demo of the feature before it goes live.
        - No, you can push the feature directly to production without a review from me.
      multiple: false
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Is your feature / client request related to a problem? Please describe."
      description: >
        A clear and concise description of what the problem is.  
        _Example: I'm always frustrated when [...]_
    validations:
      required: false

  - type: textarea
    attributes:
      label: "Describe the solution you'd like"
      description: >
        A clear and concise description of what you want to happen.
    validations:
      required: false

  - type: textarea
    attributes:
      label: "Describe alternatives you've considered"
      description: >
        A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false

  - type: textarea
    attributes:
      label: "Screenshots or a link to a Loom Recording"
      description: |
        Add any other context or screenshots about the feature request here.  
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
